name: GenesisRandomization
version: '${version}'
main: me.dueris.genesis.GenesisRandomization
api-version: '1.20'
authors: [ Dueris ]
description: Randomizes the choosing process for the origins plugin, GenesisMC
website: https://ko-fi.com/dueris
load: POSTWORLD
has-open-classloader: true
dependencies:
  server:
    GenesisMC:
      load: BEFORE
      required: true
      join-classpath: true
